### ISSUE TITLE
Missing DifferentiableAdam Class in optimizer Module

### ISSUE THREAD

**Issue by helloworld12358** [huanranchen/DiffusionClassifier#4]
Hi!

I hope you're doing well. I've been working with the DiffusionClassifier repository and encountered an issue while running the code. Specifically, I'm running into an error related to the DifferentiableAdam class, which seems to be missing from the optimizer module.

When I attempt to run the DCTK.py script, I get the following error:
ImportError: cannot import name 'DifferentiableAdam' from 'optimizer'

After checking the optimizer/__init__.py file, I noticed that the DifferentiableAdam class is not imported or defined anywhere within the module. 

If DifferentiableAdam is no longer used or has been deprecated, I'd appreciate guidance on how to resolve this issue.

Thanks.

**Comment by huanranchen** [comment]
Hi, DifferentiableAdam is not the code implementation of this paper. Instead, it is the implementation of another paper.

You can remove the related code to fix this issue.
